name: backup

on: [push, delete]

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: "0"
      - uses: ruicsh/backup-action@main
        with:
          target_repo_url: git@bitbucket.org:tuplo/numberfmt.git
          ssh_private_key: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}